### ISSUE TITLE
0.49.1 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [openstreetmap/osmosis#138]
👋 it looks like 0.49.1 release did not get completed, ie the release did not get marked as latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/154032

**Comment by brettch** [comment]
Hi @chenrui333,

I explained this in the last issue you raised on the same topic:
https://github.com/openstreetmap/osmosis/issues/136#issuecomment-1793857470

0.49.0 is the latest version. I created a 0.49.1 in order to fix Maven Central publishing but the software is identical. There's no need to release 0.49.1.

Please let me know if I'm misunderstanding something.
