### ISSUE TITLE
DEL in keys not preserved in replication diffs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osmosis#75]
When a change is made to create an object that has keys which contain DEL U+007F control characters, Osmosis strips the control characters. One place this shows up is if two keys differ only by DEL characters, then Osmosis emits two `<tag/>` elements with the same `k` value.

As an example, in changeset 90486873 a node was introduced with the tags

```xml
   <tag k="shelter_type" v="weather_shelter"/>
   <tag k="shelter_type^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?" v="lean_to"/> 
```

where the ^? are the DEL character (U+007F). 

This can be seen with the shell command `curl -s https://www.openstreetmap.org/api/0.6/node/7881523719/3 | less`, but most browsers will hide the characters.

This was transmitted out in the minutely replication feed with sequence number 004183898. If this is examined with `curl -s https://planet.openstreetmap.org/replication/minute/004/183/898.osc.gz | zcat | less -p 90486873'
this reveals the XML

```xml
      <tag k="shelter_type" v="weather_shelter"/>
      <tag k="shelter_type" v="lean_to"/> 
```

This XML does not contain the DEL characters, and has two keys which are the same. We found this because it was resulting in a duplicate key error, but aside from that Osmosis is producing results inconsistent with what is in the database.

**Comment by pnorman** [comment]
Closing because the OSMF is moving away from Osmosis for replication diffs.

**Comment by mmd-osm** [comment]
Hourly and daily diffs are still being generated via osmosis, if https://github.com/openstreetmap/operations/issues/475#issuecomment-741656374 still reflects the latest status. In that case, the issue in omosis would still occur for those file types because of https://github.com/openstreetmap/osmosis/blob/master/osmosis-xml/src/main/java/org/openstreetmap/osmosis/xml/common/ElementWriter.java#L41
