### ISSUE TITLE
Extract data from osm changes with a bounding box

### ISSUE THREAD

**Issue by Xevib** [openstreetmap/osmosis#77]
# Description 
- It would be great to be able to filter the information on a change file using with a bounding box. Now it can only be done with entity stream(https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#--bounding-box_.28--bb.29)

**Comment by brettch** [comment]
Hi @Xevib.  It would be great, but the reason it isn't implemented is because there isn't enough information in a change file/stream to implement bounding box filtering.  Way and relations don't have any location information to indicate whether they are inside or outside the bounding box.  Something like this would need access to a backing store that allows indexed lookups of related nodes such as that provided by the [Snapshot Schema](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#PostGIS_Tasks_.28Snapshot_Schema.29).

**Comment by Andygol** [comment]
I faced with the same issue while I've tried to update my local extract with replications from planet osm. (more details, see [post on community.openstreetmap](https://community.openstreetmap.org/t/deficiencies-of-the-current-data-schema-and-imperfections-of-osmosis-that-do-not-allow-cutting-the-stream-of-changes-by-bounding-polygon-to-keep-up-regional-extract-with-upstream-db/9316/10?u=andygol)).

I see the next workflow to overcome the issue in [--bb](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#--bounding-box_(--bb))/[--bp](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#--bounding-polygon_(--bp)):
* read diffs from replication stream or from local `*.osc`
* read from local API DB or from source data file (xml/pbf) 
* for the nodes in the replication stream, check if they are inside a bbox or a bounding polygon; discard all nodes outside the bbox (bounding polygon); write nodes to the target file or database.
* add newly created ways/relations according to the entry of their nodes in the bbox  (members in the source file/db).
* for ways/relations that have been changed/deleted and therefore have only references to the nodes used to reproduce their geometry, check for nodes in the source data, if such nodes are not present—discard such ways/relations and do not write them to the target database or file.
* apply `completeWays`, `completeRelations`, `cascadingRelations`, `clipIncompleteEntities` rules to keep data integrity
